sum-coverage doesnt have -t
Error: unknown shorthand flag: 't' in -t
Usage:
  cc-test-reporter sum-coverage [flags]

Flags:
  -o, --output string   output path (default "coverage/codeclimate.json")
  -p, --parts int       total number of parts to sum

Global Flags:
  -d, --debug   run in debug mode

Signed-off-by: Miah Johnson <miah@chia-pet.org>